<a href="https://colab.research.google.com/github/suyog45gt/CSITAN_Aurdino_workshop/blob/main/02)dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/colab dataset/results.csv")
schema_df=pd.read_csv("/content/drive/MyDrive/colab dataset/schema.csv")

In [ ]:
pd.set_option("display.max_columns",85)
pd.set_option("display.max_rows",85)

In [ ]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [ ]:
schema_df

                    Column                                       QuestionText
0               Respondent  Randomized respondent ID number (not in order ...
1               MainBranch  Which of the following options best describes ...
2                 Hobbyist                            Do you code as a hobby?
3              OpenSourcer        How often do you contribute to open source?
4               OpenSource  How do you feel about the quality of open sour...
5               Employment  Which of the following best describes your cur...
6                  Country          In which country do you currently reside?
7                  Student  Are you currently enrolled in a formal, degree...
8                  EdLevel  Which of the following best describes the high...
9           UndergradMajor  What was your main or most important field of ...
10                EduOther  Which of the following types of non-degree edu...
11                 OrgSize  Approximately how many people are employed by ...
12                 DevType  Which of the following describe you? Please se...
13               YearsCode  Including any education, how many years have y...
14              Age1stCode  At what age did you write your first line of c...
15            YearsCodePro  How many years have you coded professionally (...
16               CareerSat  Overall, how satisfied are you with your caree...
17                  JobSat  How satisfied are you with your current job? (...
18                MgrIdiot  How confident are you that your manager knows ...
19                MgrMoney  Do you believe that you need to be a manager t...
20                 MgrWant  Do you want to become a manager yourself in th...
21                 JobSeek  Which of the following best describes your cur...
22            LastHireDate  When was the last time that you took a job wit...
23                 LastInt  In your most recent successful job interview (...
24                FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
25              JobFactors  Imagine that you are deciding between two job ...
26            ResumeUpdate  Think back to the last time you updated your r...
27          CurrencySymbol  Which currency do you use day-to-day? If your ...
28            CurrencyDesc  Which currency do you use day-to-day? If your ...
29               CompTotal  What is your current total compensation (salar...
30                CompFreq   Is that compensation weekly, monthly, or yearly?
31           ConvertedComp  Salary converted to annual USD salaries using ...
32             WorkWeekHrs   On average, how many hours per week do you work?
33                WorkPlan            How structured or planned is your work?
34           WorkChallenge  Of these options, what are your greatest chall...
35              WorkRemote                    How often do you work remotely?
36                 WorkLoc                    Where would you prefer to work?
37                  ImpSyn  For the specific work you do, and the years of...
38                 CodeRev           Do you review code as part of your work?
39              CodeRevHrs  On average, how many hours per week do you spe...
40               UnitTests  Does your company regularly employ unit tests ...
41             PurchaseHow  How does your company make decisions about pur...
42            PurchaseWhat  What level of influence do you, personally, ha...
43      LanguageWorkedWith  Which of the following programming, scripting,...
44  LanguageDesireNextYear  Which of the following programming, scripting,...
45      DatabaseWorkedWith  Which of the following database environments h...
46  DatabaseDesireNextYear  Which of the following database environments h...
47      PlatformWorkedWith  Which of the following platforms have you done...
48  PlatformDesireNextYear  Which of the following platforms have you done...
49      WebFrameWorkedWith  Which of the following web frameworks have you...
50  WebFrameDesireNextYear  Which of the following web frameworks have you...
51      MiscTechWorkedWith  Which of the following other frameworks, libra...
52  MiscTechDesireNextYear  Which of the following other frameworks, libra...
53              DevEnviron  Which development environment(s) do you use re...
54                   OpSys  What is the primary operating system in which ...
55              Containers  How do you use containers (Docker, Open Contai...
56           BlockchainOrg  How is your organization thinking about or imp...
57            BlockchainIs  Blockchain / cryptocurrency technology is prim...
58              BetterLife  Do you think people born today will have a bet...
59                ITperson   Are you the "IT support person" for your family?
60                   OffOn        Have you tried turning it off and on again?
61             SocialMedia        What social media site do you use the most?
62            Extraversion    Do you prefer online chat or IRL conversations?
63              ScreenName                               What do you call it?
64              SOVisit1st  To the best of your memory, when did you first...
65             SOVisitFreq  How frequently would you say you visit Stack O...
66               SOVisitTo  I visit Stack Overflow to... (check all that a...
67            SOFindAnswer  On average, how many times a week do you find ...
68             SOTimeSaved  Think back to the last time you solved a codin...
69           SOHowMuchTime  About how much time did you save? If you're no...
70               SOAccount              Do you have a Stack Overflow account?
71              SOPartFreq  How frequently would you say you participate i...
72                  SOJobs  Have you ever used or visited Stack Overflow J...
73                EntTeams  Have you ever used Stack Overflow for Enterpri...
74                  SOComm  Do you consider yourself a member of the Stack...
75           WelcomeChange  Compared to last year, how welcome do you feel...
76            SONewContent  Would you like to see any of the following on ...
77                     Age  What is your age (in years)? If you prefer not...
78                  Gender  Which of the following do you currently identi...
79                   Trans                    Do you identify as transgender?
80               Sexuality  Which of the following do you currently identi...
81               Ethnicity  Which of the following do you identify as? Ple...
82              Dependents  Do you have any dependents (e.g., children, el...
83            SurveyLength  How do you feel about the length of the survey...
84              SurveyEase  How easy or difficult was this survey to compl...

In [ ]:
df.shape

(88883, 85)

In [ ]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [ ]:
df["Hobbyist"]

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [ ]:
df.loc[0]#first row

Respondent                                                                1
MainBranch                           I am a student who is learning to code
Hobbyist                                                                Yes
OpenSourcer                                                           Never
OpenSource                The quality of OSS and closed source software ...
Employment                           Not employed, and not looking for work
Country                                                      United Kingdom
Student                                                                  No
EdLevel                                           Primary/elementary school
UndergradMajor                                                          NaN
EduOther                  Taught yourself a new language, framework, or ...
OrgSize                                                                 NaN
DevType                                                                 NaN
YearsCode                                                                 4
Age1stCode                                                               10
YearsCodePro                                                            NaN
CareerSat                                                               NaN
JobSat                                                                  NaN
MgrIdiot                                                                NaN
MgrMoney                                                                NaN
MgrWant                                                                 NaN
JobSeek                                                                 NaN
LastHireDate                                                            NaN
LastInt                                                                 NaN
FizzBuzz                                                                NaN
JobFactors                                                              NaN
ResumeUpdate                                                            NaN
CurrencySymbol                                                          NaN
CurrencyDesc                                                            NaN
CompTotal                                                               NaN
CompFreq                                                                NaN
ConvertedComp                                                           NaN
WorkWeekHrs                                                             NaN
WorkPlan                                                                NaN
WorkChallenge                                                           NaN
WorkRemote                                                              NaN
WorkLoc                                                                 NaN
ImpSyn                                                                  NaN
CodeRev                                                                 NaN
CodeRevHrs                                                              NaN
UnitTests                                                               NaN
PurchaseHow                                                             NaN
PurchaseWhat                                                            NaN
LanguageWorkedWith                          HTML/CSS;Java;JavaScript;Python
LanguageDesireNextYear      C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL
DatabaseWorkedWith                                                   SQLite
DatabaseDesireNextYear                                                MySQL
PlatformWorkedWith                                            MacOS;Windows
PlatformDesireNextYear                              Android;Arduino;Windows
WebFrameWorkedWith                                             Django;Flask
WebFrameDesireNextYear                                         Flask;jQuery
MiscTechWorkedWith                                                  Node.js
MiscTechDesireNextYear                                              Node.js
DevEnviron                                       IntelliJ;Notepad++;PyCharm
OpSys                                                               Windows
Containers                                          I do not use containers
BlockchainOrg                                                           NaN
BlockchainIs                                                            NaN
BetterLife                                                              Yes
ITperson                           Fortunately, someone else has that title
OffOn                                                                   Yes
SocialMedia                                                         Twitter
Extraversion                                                         Online
ScreenName                                                         Username
SOVisit1st                                                             2017
SOVisitFreq                                 A few times per month or weekly
SOVisitTo                 Find answers to specific questions;Learn how t...
SOFindAnswer                                             3-5 times per week
SOTimeSaved                                  Stack Overflow was much faster
SOHowMuchTime                                                 31-60 minutes
SOAccount                                                                No
SOPartFreq                                                              NaN
SOJobs                    No, I didn't know that Stack Overflow had a jo...
EntTeams                                No, and I don't know what those are
SOComm                                                              Neutral
WelcomeChange                       Just as welcome now as I felt last year
SONewContent              Tech articles written by other developers;Indu...
Age                                                                    14.0
Gender                                                                  Man
Trans                                                                    No
Sexuality                                           Straight / Heterosexual
Ethnicity                                                               NaN
Dependents                                                               No
SurveyLength                                          Appropriate in length
SurveyEase                                       Neither easy nor difficult
Name: 0, dtype: object

In [ ]:
df.loc[0,"Hobbyist"]#first row of given column

'Yes'

In [ ]:
df.loc[[0,1,2],"Hobbyist"]#first,second and third row of given column

0    Yes
1     No
2    Yes
Name: Hobbyist, dtype: object

In [ ]:
df.loc[0:2,"Hobbyist":'Country']#first to third row of given column

,Hobbyist,OpenSourcer,OpenSource,Employment,Country
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand